#!/usr/bin/env python3
"""
System Prompt Extraction Script

This script extracts and reconstructs the complete system prompt that would be
generated by the VS Code extension and sent to the LLM. It simulates the
TypeScript system prompt generation logic in Python.
"""

import os
import re
import json
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from config import SystemPromptConfig
from section_parsers import SectionParsers


@dataclass
class GeneratedSections:
    """Container for all generated prompt sections"""
    role_definition: str = ""
    markdown_formatting: str = ""
    shared_tool_use: str = ""
    tool_descriptions: str = ""
    tool_use_guidelines: str = ""
    morph_instructions: str = ""
    mcp_servers: str = ""
    capabilities: str = ""
    modes: str = ""
    rules: str = ""
    system_info: str = ""
    objective: str = ""
    custom_instructions: str = ""


class SystemPromptExtractor:
    """Main class for extracting and generating the system prompt"""
    
    def __init__(self, config: SystemPromptConfig):
        self.config = config
        self.parsers = SectionParsers(config)
        self.sections = GeneratedSections()
        
    def generate_complete_prompt(self) -> str:
        """Generate the complete system prompt by assembling all sections"""
        print("Generating system prompt sections...")
        
        # Generate each section
        self._generate_role_definition()
        self._generate_markdown_formatting()
        self._generate_shared_tool_use()
        self._generate_tool_descriptions()
        self._generate_tool_use_guidelines()
        self._generate_morph_instructions()
        self._generate_mcp_servers()
        self._generate_capabilities()
        self._generate_modes()
        self._generate_rules()
        self._generate_system_info()
        self._generate_objective()
        self._generate_custom_instructions()
        
        # Assemble the complete prompt following the TypeScript logic
        prompt_parts = [
            self.sections.role_definition,
            "",
            self.sections.markdown_formatting,
            "",
            self.sections.shared_tool_use,
            "",
            self.sections.tool_descriptions,
            "",
            self.sections.tool_use_guidelines,
            "",
            self.sections.morph_instructions,
            self.sections.mcp_servers,
            "",
            self.sections.capabilities,
            "",
            self.sections.modes,
            "",
            self.sections.rules,
            "",
            self.sections.system_info,
            "",
            self.sections.objective,
            "",
            self.sections.custom_instructions
        ]
        
        # Join parts and clean up extra whitespace
        complete_prompt = "\n".join(prompt_parts)
        complete_prompt = re.sub(r'\n{3,}', '\n\n', complete_prompt)  # Max 2 consecutive newlines
        
        return complete_prompt.strip()
    
    def _generate_role_definition(self):
        """Generate role definition based on mode"""
        print("  - Generating role definition...")
        mode_data = self.parsers.get_mode_data(self.config.mode)
        self.sections.role_definition = mode_data.get("roleDefinition", "")
    
    def _generate_markdown_formatting(self):
        """Generate markdown formatting section"""
        print("  - Generating markdown formatting section...")
        self.sections.markdown_formatting = self.parsers.parse_markdown_formatting_section()
    
    def _generate_shared_tool_use(self):
        """Generate shared tool use section"""
        print("  - Generating shared tool use section...")
        self.sections.shared_tool_use = self.parsers.parse_shared_tool_use_section()
    
    def _generate_tool_descriptions(self):
        """Generate tool descriptions for the specified mode"""
        print("  - Generating tool descriptions...")
        self.sections.tool_descriptions = self.parsers.generate_tool_descriptions()
    
    def _generate_tool_use_guidelines(self):
        """Generate tool use guidelines section"""
        print("  - Generating tool use guidelines...")
        self.sections.tool_use_guidelines = self.parsers.parse_tool_use_guidelines_section()
    
    def _generate_morph_instructions(self):
        """Generate morph instructions if enabled"""
        print("  - Generating morph instructions...")
        if self.config.experiments.get("morphFastApply", False):
            self.sections.morph_instructions = self.parsers.parse_morph_instructions()
        else:
            self.sections.morph_instructions = ""
    
    def _generate_mcp_servers(self):
        """Generate MCP servers section if applicable"""
        print("  - Generating MCP servers section...")
        if self.config.enable_mcp_server_creation:
            self.sections.mcp_servers = self.parsers.parse_mcp_servers_section()
        else:
            self.sections.mcp_servers = ""
    
    def _generate_capabilities(self):
        """Generate capabilities section"""
        print("  - Generating capabilities section...")
        self.sections.capabilities = self.parsers.parse_capabilities_section()
    
    def _generate_modes(self):
        """Generate modes section"""
        print("  - Generating modes section...")
        self.sections.modes = self.parsers.parse_modes_section()
    
    def _generate_rules(self):
        """Generate rules section"""
        print("  - Generating rules section...")
        self.sections.rules = self.parsers.parse_rules_section()
    
    def _generate_system_info(self):
        """Generate system info section"""
        print("  - Generating system info section...")
        self.sections.system_info = self.parsers.parse_system_info_section()
    
    def _generate_objective(self):
        """Generate objective section"""
        print("  - Generating objective section...")
        self.sections.objective = self.parsers.parse_objective_section()
    
    def _generate_custom_instructions(self):
        """Generate custom instructions section"""
        print("  - Generating custom instructions...")
        self.sections.custom_instructions = self.parsers.parse_custom_instructions()
    
    def save_prompt_to_file(self, prompt: str, output_path: str):
        """Save the generated prompt to a markdown file"""
        print(f"Saving prompt to {output_path}...")
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# Generated System Prompt\n\n")
            f.write("This is the complete system prompt that would be sent to the LLM.\n\n")
            f.write("---\n\n")
            f.write(prompt)
        
        print(f"System prompt saved to: {output_path}")
    
    def save_analysis_to_file(self, output_path: str):
        """Save a detailed analysis of each section to a file"""
        print(f"Saving analysis to {output_path}...")
        
        analysis_content = [
            "# System Prompt Analysis\n",
            "This file provides a breakdown of each section in the generated system prompt.\n",
            f"Generated with configuration: {self.config.mode} mode\n\n",
            "---\n\n"
        ]
        
        sections_info = [
            ("Role Definition", self.sections.role_definition, "Defines the AI assistant's role and identity"),
            ("Markdown Formatting", self.sections.markdown_formatting, "Rules for formatting responses"),
            ("Shared Tool Use", self.sections.shared_tool_use, "General tool usage instructions"),
            ("Tool Descriptions", self.sections.tool_descriptions, "Detailed descriptions of available tools"),
            ("Tool Use Guidelines", self.sections.tool_use_guidelines, "Guidelines for effective tool usage"),
            ("Morph Instructions", self.sections.morph_instructions, "Fast apply editing instructions"),
            ("MCP Servers", self.sections.mcp_servers, "Model Context Protocol server information"),
            ("Capabilities", self.sections.capabilities, "Overview of assistant capabilities"),
            ("Modes", self.sections.modes, "Available modes and their descriptions"),
            ("Rules", self.sections.rules, "Operating rules and constraints"),
            ("System Info", self.sections.system_info, "System and environment information"),
            ("Objective", self.sections.objective, "Task completion methodology"),
            ("Custom Instructions", self.sections.custom_instructions, "Custom user and mode instructions")
        ]
        
        for title, content, description in sections_info:
            analysis_content.extend([
                f"## {title}\n\n",
                f"**Description:** {description}\n\n",
                f"**Content Length:** {len(content)} characters\n\n",
                "**Content:**\n\n",
                "```\n",
                content if content else "(Empty section)",
                "\n```\n\n",
                "---\n\n"
            ])
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.writelines(analysis_content)
        
        print(f"Analysis saved to: {output_path}")


def main():
    """Main function to run the system prompt extraction"""
    print("Starting system prompt extraction...")
    
    # Load configuration
    config = SystemPromptConfig()
    
    # Create extractor
    extractor = SystemPromptExtractor(config)
    
    # Generate the complete prompt
    prompt = extractor.generate_complete_prompt()
    
    # Save outputs
    output_dir = Path(__file__).parent
    prompt_file = output_dir / "generated-system-prompt.md"
    analysis_file = output_dir / "prompt-analysis.md"
    
    extractor.save_prompt_to_file(prompt, str(prompt_file))
    extractor.save_analysis_to_file(str(analysis_file))
    
    print(f"\nExtraction complete!")
    print(f"Generated prompt: {len(prompt)} characters")
    print(f"Files saved in: {output_dir}")


if __name__ == "__main__":
    main()